name: Gradle Build Action
description: A sample GitHub Action written in Bash

inputs:
  build-and-test:
    description: "Set to true if you want to run build and not exclude the check task"
    required: false
    default: "false"
  jacoco-csv-location:
    description: "Location of Jacoco CSV report, only used if BUILD_AND_TEST is set to true"
    required: false
    default: "./build/reports/jacoco/test/jacocoTestReport.csv"
outputs:
  total-lines:
    description: "Total lines to cover with tests, only set if BUILD_AND_TEST is set to true"
    value: ${{ steps.build_and_test.outputs.total-lines }}
  lines-covered:
    description: "Total lines to covered with tests, only set if BUILD_AND_TEST is set to true"
    value: ${{ steps.build_and_test.outputs.lines-covered }}
  coverage-percentage:
    description: "The coverage percentage, only set if BUILD_AND_TEST is set to true"
    value: ${{ steps.build_and_test.outputs.coverage-percentage }}

runs:
  using: composite
  steps:
    - name: "Setup Java"
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: "Setup Gradle"
      uses: gradle/actions/setup-gradle@v4

    - name: "Run build and tests"
      id: build_and_test
      run: |
        ./gradlew --build-cache build
        if [ -f ${{ inputs.jacoco-csv-location }} ]; then
          awk -F "," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' ${{ inputs.jacoco-csv-location }}
          echo "total-lines=$(awk -F "," '{ instructions += $4 + $5 } END { print instructions }' ${{ inputs.jacoco-csv-location }})" >> "$GITHUB_OUTPUT"
          echo "lines-covered=$(awk -F "," '{ covered += $5 } END { print covered }' ${{ inputs.jacoco-csv-location }})" >> "$GITHUB_OUTPUT"
          echo "coverage-percentage=$(awk -F "," '{ instructions += $4 + $5; covered += $5 } END { print 100*covered/instructions }' ${{ inputs.jacoco-csv-location }})" >> "$GITHUB_OUTPUT"
        else
          echo -e "\e[33mJacoco CSV coverage report not found!\e[0m"
        fi
      if: ${{ inputs.build-and-test == 'true' }}
      shell: bash

    - name: "Run build"
      run: |
        ./gradlew --build-cache build testClasses -x check
      if: ${{ inputs.build-and-test != 'true' }}
      shell: bash

    - name: Report Status Check
      if: always()
      uses: phorus-group/workflow-status-check-action@main
      with:
        state: ${{ steps.action.outcome }}

    - name: "Prepare branch name"
      id: prepare_branch_name
      uses: phorus-group/unslash-text-action@main
      with:
        text: ${{ github.head_ref || github.ref_name }}

    - name: "Upload build artifact"
      uses: actions/upload-artifact@master
      with:
        name: gradle-build-${{ steps.prepare_branch_name.outputs.text }}
        retention-days: 2
        path: build/libs/*.jar
