name: Verify Bash Action

on:
  pull_request:
    branches:
      - main
    types: [ opened, edited, synchronize ]
  push:
  workflow_dispatch:

jobs:
  static_checks:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: bash formatting
        run: docker run -v "$PWD":/mnt -w /mnt mvdan/shfmt -ci -i 2 -l -d -- *.sh

      - name: shellcheck
        run: docker run -v "$PWD":/mnt -w /mnt koalaman/shellcheck -- *.sh test/*.bats

      - name: misc files formatting
        run: docker run -v "$PWD":/mnt -w /mnt tmknom/prettier --check .

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.11.0

      - name: Run Tests
        run: bats --trace --print-output-on-failure test/

  self_check:
    name: Run this Action
    runs-on: ubuntu-latest
    needs: [static_checks, tests]
    steps:
      - uses: actions/checkout@v2

      - name: "Clone test project"
        uses: actions/checkout@v2
        repository: "phorus-group/mapper"
        path: "mapper"

      - name: "Call action"
        uses: ./
        with:
          BUILD_AND_TEST: true

      - name: Set status output for reporting
        id: set_status
        run: |
          # Check the exit code of the previous step
          if [ $? -eq 0 ]; then
            echo "status=success" >> "$GITHUB_ENV"
          else
            echo "status=failure" >> "$GITHUB_ENV"
          fi

  report_status:
    name: Report Status Check
    runs-on: ubuntu-latest
    needs: [self_check]
    steps:
      - name: Report Status Check
        if: always()
        run: |
          $CHECK_NAME="${{ github.workflow }}"
          STATE="${{ needs.self_check.outputs.status }}"
          DESCRIPTION="Workflow state - ${STATE}."

          CHECK_RUN_ID=$(gh api --method POST /repos/${{ github.repository }}/check-runs \
            -f name="$CHECK_NAME" \
            -f head_sha="${{ github.sha }}" \
            -f status="completed" \
            -f conclusion="$STATE" \
            -f output.summary="$DESCRIPTION" \
            -f output.text="$DESCRIPTION" \
            -f output.title="Workflow Status" \
            -q '.id')

          echo "Check created with ID: $CHECK_RUN_ID"