name: Verify Bash Action

on:
  pull_request:
  workflow_dispatch:

jobs:
  self_check:
    name: Run this Action
    runs-on: ubuntu-latest
    steps:
      - name: "Clone test project"
        uses: actions/checkout@v4
        with:
          repository: phorus-group/mapper

      - name: "Clone action"
        uses: actions/checkout@v4
        with:
          path: action
          clean: false

      - name: "Call action"
        uses: ./action
        with:
          BUILD_AND_TEST: true

      - name: Set status output for reporting
        id: set_status
        if: always()
        run: |
          # Check the exit code of the previous step
          if [ $? -eq 0 ]; then
            echo "ye"
            echo "status=success" >> "$GITHUB_ENV"
          else
            echo "no"
            echo "status=failure" >> "$GITHUB_ENV"
          fi

  report_status:
    name: Report Status Check
    runs-on: ubuntu-latest
    needs: [self_check]
    if: always()
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Report Status Check
        if: always()
        run: |
          CHECK_NAME="${{ github.workflow }}"
          STATE="${{ needs.self_check.outputs.status }}"
          DESCRIPTION="Workflow state - ${STATE}."

          CHECK_RUN_ID=$(gh api --method POST /repos/${{ github.repository }}/check-runs \
            -f name="$CHECK_NAME" \
            -f head_sha="${{ github.sha }}" \
            -f status="completed" \
              -f conclusion="$STATE" \
            -f output.summary="$DESCRIPTION" \
            -f output.text="$DESCRIPTION" \
            -f output.title="Workflow Status" \
            -q '.id')

          echo "Check created with ID: $CHECK_RUN_ID"