name: Verify Bash Action

on:
  pull_request:
  workflow_dispatch:

jobs:
  self_check:
    name: Run this Action
    runs-on: ubuntu-latest
    steps:
      - name: "Clone test project"
        uses: actions/checkout@v4
        with:
          repository: phorus-group/mapper

      - name: "Clone action"
        uses: actions/checkout@v4
        with:
          path: action
          clean: false

      - name: "Call action"
        id: action
        uses: ./action
        with:
          BUILD_AND_TEST: true

      - name: Report Status Check
        if: always()
        run: |
          CHECK_NAME="${{ github.workflow }}"
          STATE="${{ steps.action.outcome }}"
          
          echo "The '$CHECK_NAME' state is - $STATE"

          DESCRIPTION="Workflow state - ${STATE}."

          GH_TOKEN: ${{ github.token }}
          CHECK_RUN_ID=$(gh api --method POST /repos/${{ github.repository }}/check-runs \
            -f name="$CHECK_NAME" \
            -f head_sha="${{ github.sha }}" \
            -f status="completed" \
              -f conclusion="$STATE" \
            -f output.summary="$DESCRIPTION" \
            -f output.text="$DESCRIPTION" \
            -f output.title="Workflow Status" \
            -q '.id')

          echo "Check created with ID: $CHECK_RUN_ID"
